In [5]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt

from tqdm import tqdm
from sklearn.model_selection import train_test_split

In [6]:
df = pd.read_csv('housing.csv')
df.head()

,0.00632,18,2.31,0,0.538,6.575,65.2,4.09,1,296,15.3,396.9,4.98,24
0,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
1,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
2,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
3,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
4,0.02985,0.0,2.18,0,0.458,6.430,58.7,6.0622,3,222,18.7,394.12,5.21,28.7

In [7]:
#EDA

In [8]:
for i in tqdm(range(1000000)):
    pass

100%|██████████| 1000000/1000000 [00:00<00:00, 3816938.55it/s]

In [9]:
df.describe()

,0.00632,18,2.31,0,0.538,6.575,65.2,4.09,1,296,15.3,396.9,4.98,24
count,505.000000,505.000000,505.000000,505.000000,505.000000,505.000000,505.000000,505.000000,505.000000,505.000000,505.000000,505.000000,505.000000,505.000000
mean,3.620663,11.350495,11.154257,0.069307,0.554728,6.284059,68.581584,3.794460,9.566337,408.459406,18.461782,356.594376,12.668257,22.529901
std,8.608569,23.343704,6.855868,0.254227,0.115990,0.703195,28.176371,2.107761,8.707553,168.629992,2.162520,91.367787,7.139950,9.205991
min,0.009060,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082210,0.000000,5.190000,0.000000,0.449000,5.885000,45.000000,2.100000,4.000000,279.000000,17.400000,375.330000,7.010000,17.000000
50%,0.259150,0.000000,9.690000,0.000000,0.538000,6.208000,77.700000,3.199200,5.000000,330.000000,19.100000,391.430000,11.380000,21.200000
75%,3.678200,12.500000,18.100000,0.000000,0.624000,6.625000,94.100000,5.211900,24.000000,666.000000,20.200000,396.210000,16.960000,25.000000
max,88.976000,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.127000,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [10]:
df.corr()

,0.00632,18,2.31,0,0.538,6.575,65.2,4.09,1,296,15.3,396.9,4.98,24
0.00632,1.000000,-0.200283,0.406251,-0.056132,0.420934,-0.218978,0.352701,-0.379626,0.625395,0.582568,0.289393,-0.384838,0.455328,-0.388249
18,-0.200283,1.000000,-0.534022,-0.042550,-0.516574,0.311835,-0.569524,0.664396,-0.311717,-0.314351,-0.391713,0.175319,-0.412894,0.360393
2.31,0.406251,-0.534022,1.000000,0.062350,0.764556,-0.391330,0.645543,-0.708848,0.594167,0.720561,0.380955,-0.356506,0.602737,-0.484126
0,-0.056132,-0.042550,0.062350,1.000000,0.091134,0.091497,0.086461,-0.099109,-0.007907,-0.035965,-0.122570,0.049040,-0.054576,0.175364
0.538,0.420934,-0.516574,0.764556,0.091134,1.000000,-0.302127,0.731461,-0.769220,0.611758,0.668141,0.188918,-0.380006,0.591262,-0.427295
6.575,-0.218978,0.311835,-0.391330,0.091497,-0.302127,1.000000,-0.240211,0.205170,-0.209277,-0.291680,-0.355116,0.127754,-0.613734,0.695365
65.2,0.352701,-0.569524,0.645543,0.086461,0.731461,-0.240211,1.000000,-0.747872,0.456232,0.506527,0.261724,-0.273486,0.602782,-0.376932
4.09,-0.379626,0.664396,-0.708848,-0.099109,-0.769220,0.205170,-0.747872,1.000000,-0.494797,-0.534492,-0.232560,0.291451,-0.497276,0.249895
1,0.625395,-0.311717,0.594167,-0.007907,0.611758,-0.209277,0.456232,-0.494797,1.000000,0.910202,0.463322,-0.444065,0.487608,-0.381690
296,0.582568,-0.314351,0.720561,-0.035965,0.668141,-0.291680,0.506527,-0.534492,0.910202,1.000000,0.460100,-0.441505,0.543435,-0.468543
15.3,0.289393,-0.391713,0.380955,-0.122570,0.188918,-0.355116,0.261724,-0.232560,0.463322,0.460100,1.000000,-0.176515,0.372148,-0.508411
396.9,-0.384838,0.175319,-0.356506,0.049040,-0.380006,0.127754,-0.273486,0.291451,-0.444065,-0.441505,-0.176515,1.000000,-0.365637,0.333394
4.98,0.455328,-0.412894,0.602737,-0.054576,0.591262,-0.613734,0.602782,-0.497276,0.487608,0.543435,0.372148,-0.365637,1.000000,-0.738187
24,-0.388249,0.360393,-0.484126,0.175364,-0.427295,0.695365,-0.376932,0.249895,-0.381690,-0.468543,-0.508411,0.333394,-0.738187,1.000000

In [11]:
class LinearRegression:
    def __init__(self, X, y, learningrate, tolerance, maxIteration = 50000, error = 'rmse', gd = False):
        self.X = X
        self.y = y
        self.learningrate = learningrate
        self.tolerance = tolerance
        self.maxIteration = maxIteration
        self.error = error
        self.gd = gd
    #容忍度是为了防止多重共线性回归的：即因变量之间存在线性回归关系# 
    def trainTestSplit(self, X, y):
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)#random_state 为了保证每次分割都是相同的训练集和测试集#
        
        return X_train, X_test, y_train, y_test
    
    def addX0(self, X):
        """
        @X : numpy matrix, dataset
        @does: add a bias term to the data
        @return :numpy matrix
        """
        return np.column_stack([np.ones([X.shape[0], 1]), X])
        
    def normalize(self, X):
        """
        @X : numpy matrix, dataset
        @does: normalize the data
        @return :numpy matrix, array, array
        """
        #归一化#
        
        mean = np.mean(X, 0)
        std = np.std(X,0)
        X_norm = (X - mean)/std
        X_norm = self.addX0(X_norm)
        
        return X_norm, mean, std
    
    def normalizeTestData(self, X, trainMean, trainStd):
        """
        @X : numpy matrix, dataset
        @does: normalize the test data
        @return :numpy matrix
        """
        X_norm = (X - trainMean)/ trainStd
        X_norm = self.addX0(X_norm)
        
        return X_norm
    
    def rank(self, X, eps = 1e-12):
        u, S, vh = np.linalg.svd(X)
        return len([x for x in S if abs(x) > eps])
    
    def checkMatrix(self, X):
        X_rank = self.rank(X)
        if X_rank == min(X.shape[0], X.shape[1]):#检查是否位满秩矩阵#
            self.fullRank = True
            print('Matrix is full rank')
        else:
            self.fullRank = False
            print('Matrix is not full rank')
            
    def checkInvertibility(self, X):
        if X.shape[0] < X.shape[1]:
            self.lowRank = True
            print('The matrix is low rank')
        else:
            self.lowRank = False
            print('The matrix is not low rank') #检查矩阵是否是low rank#
    
    
    def closedFromSolution(self, X, y):
        """
        @X : numpy matrix, dataset
        @y : numpy array, target value
        @does: solve the regression using closed from solution |X^TX|^-1.X^T.y
        @return :numpy array
        """
        return np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y) #linalg是线性代数矩阵#
    
    def predict(self, X):
        return X.dot(self.w)
    
    def sse(self, X, y):
        y_hat = self.predict(X)
        return ((y_hat - y)**2).sum() #||X^T*theta - y||2
    
    def rmse(self, X, y):
        return math.sqrt(self.sse(X, y) / y.size)
        
    def costFunction(self, X, y):
        return self.sse(X, y)/2
    
    def costDeriviative(self, X, y):
        y_hat = self.predict(X)
        return (y_hat-y).dot(X) # 2X^T*theta*X - 2X^Ty
    
    
    def gradientDescent(self, X, y):
        error_sequences = []
        last_error = float('inf')
        for i in tqdm(range(self.maxIteration)):
            self.w = self.w - self.learningrate * self.costDeriviative(X, y)
            if self.error == 'rmse':
                current_error = self.rmse(X,y)
            else :
                current_error = self.sse(X,y)
            
            diff = last_error - current_error
            last_error = current_error
            
            if diff < self.tolerance:
                print("The model stopped - no further improvement")
                break
        return 
    
    def trainModel(self):
        self.X_train, self.X_test, self.y_train, self.y_test = self.trainTestSplit(self.X,self.y)
        
        #Normalize the data
        
        self.X_train, self.mean, self.std = self.normalize(self.X_train)
        self.X_test = self.normalizeTestData(self.X_test, self.mean, self.std)
        
        self.checkMatrix(self.X_train)
        self.checkInvertibility(self.X_train)
        
        if self.fullRank and not self.lowRank and self.X_train.shape[0] < 10000 and not self.gd:
            self.w = self.closedFromSolution(self.X_train, self.y_train)
        else:
            self.w = np.ones(self.X_train.shape[1], dtype=np.float64) * 0 
            self.gradientDescent(self.X_train,self.y_train)
        print(self.w)
        
        if self.error == 'rmse':
            print(self.rmse(self.X_test, self.y_test))
        else:
            print(self.sse(self.X_test, self.y_test))

In [12]:
regression = LinearRegression(df.values[:, 0:-1], df.values[:, -1], learningrate = 0.000001, tolerance = 0.0000001, gd =True, error = 'rmse')

In [13]:
regression.trainModel()

 14%|█▍        | 7212/50000 [00:00<00:00, 72117.83it/s]

Matrix is full rank
The matrix is not low rank

100%|██████████| 50000/50000 [00:00<00:00, 75291.23it/s]

[22.93399384 -0.85585755  0.94924681  0.15558472  0.69387044 -1.99584958
  2.66643306  0.38871077 -2.56419185  1.69019253 -1.03847932 -2.28731473
  0.6536851  -3.94354466]
4.638752302319916